### ISSUE TITLE
Makefile doesn't appear as an available syntax despite installing this extension

### ISSUE THREAD

**Issue by toph-allen** [stollcri/makefile.novaextension#1]
Running Nova 4.1, Makefile syntax highlighting isn't available, despite installing this extension. Don't have much more to say, sorry. 😅

**Comment by stollcri** [comment]
Yeah, Panic completely changed their language support in version 4 without letting extension developers know the change would be coming

**Comment by toph-allen** [comment]
Oop, that's not great. Thanks for the response!

**Comment by stollcri** [comment]
Fixed with https://github.com/stollcri/makefile.novaextension/commit/a643e27ce903b410a3f9f68d220dc8e558187cbe, published to extension library
